# Generated by Django 4.2.4 on 2023-08-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_song_playlist_songs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Track',
        ),
    ]
