# Generated by Django 4.2.4 on 2023-08-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_rename_song_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
